module.exports = {
	// 页面路由
	'/': 'home.jsp',
	'/box/plan/evaluate_step1': 'evaluateStep1.jsp',
	'/box/plan/evaluate_step2': 'evaluateStep2.jsp',
	'/box/plan/evaluate_step3': 'evaluateStep3.jsp',
	"/box/plan/major_exam1"   : 'majorExam1.jsp',
	"/box/plan/major_exam2"   : 'majorExam2.jsp',
	"/box/plan/major_exam3"   : 'majorExam3.jsp',
	'/user'   : 'user.jsp',
	"/box/plan/book_step2"   : 'bookStep2.jsp',
	"/box/plan/book_step1"   : 'bookStep1.jsp',
	"/box/plan/book_step3"   : 'bookStep3.jsp',
	"/box/plan/book_step4"   : 'bookStep4.jsp',
	"/library/college"   : 'college.jsp',
	"/library/college/1"   : 'collegeDetail.jsp',
	'/404'   : 'error.jsp',
	'/info'   : 'info.jsp',
	'/infoDetail'   : 'infoDetail.jsp',
	'/book'   : 'bookService.jsp',
	'/book2'   : 'bookService_success.jsp',
	"/library/major"   : 'major.jsp',
	"/library/major2"   : 'major_2.jsp',
	"/box/score_management": "score.jsp",
	"/box/plan/aboard": "aboard.jsp",
	"/box/expert_order" :"expertOrder.jsp",
	"/box/college_faq" :"collegeFaq.jsp",
	"/library/subject" : "subject.jsp",
	"/library/score_line": "scoreLine.jsp",
	"/library/aboard_data": "abordData.jsp",
	"/home/signin": "login.jsp",
	//异步加载
	'post::/v2/client/loadmore/test' : 'mock::api/test.json',
	'post::/v2/client/loadmore/history' : 'mock::api/history.json',
	'post::/v2/client/loadmore/question' : 'mock::api/question.json',
	'post::/v2/client/getCity' : 'mock::api/city.json',
	'post::/v2/client/1/data/college' : 'mock::api/college.json',
	'post::/v2/client/1/data/college/1/majors' : 'mock::api/major.json',
	'post::/v2/client/1/profile/favor/college/add' : 'mock::api/addFav.json',
	'post::/v2/client/1/profile/favor/major/add' : 'mock::api/addFav.json',
	'post::/v2/client/1/profile/favor/delete' : 'mock::api/delFav.json',
	'post::/v2/client/auth/signin' : 'mock::api/siginin.json',
	'post::/v2/client/auth/requestCode' : 'mock::ap/profile/favor/major/addi/code.json',
	'post::/v2/client/auth/signup' : 'mock::api/signup.json',
	'get::/v2/client1/data/major/all'  : 'mock::api/majorList.json',
	'post::/v2/client/1/data/major' :  'mock::api/majors.json',
	'post::/v2/client/1/data/major/college':  'mock::api/college.json'
};